version: "3.8"

services:
  fastapi_app:
    build: .
    container_name: fastapi_service
    ports:
      - "6464:6464"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
